/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mycareer: [
    'mycareer',                  // 모든 프로젝트를 한번에 볼 수 있도록 핵심만 표시
    'mycareer/mymbd',
    'mycareer/myprocess',           // 각 프로젝트 상세 내용을 기술
    'mycareer/myembedded',
  ],
  sideprj: [
    'sideprj',
	'sideprj/temperature/temperature',
    {
      type: 'category',
      label: '와이퍼 프로젝트',
	  link: {
        type: 'doc',
        id: 'sideprj/wiper',
      },
      collapsed: true,
      items: [
        'sideprj/wiper/wiper_plan',
        'sideprj/wiper/wiper_devenv',
        'sideprj/wiper/wiper_verify',
      ],
    },
    {
      type: 'category',
      label: '윈도우 프로젝트',
	  link: {
        type: 'doc',
        id: 'sideprj/window',
      },
      collapsed: true,
      items: [
        'sideprj/window/window_design',
        {
          type: 'category',
          label: '구현',
		  link: {
			type: 'doc',
			id: 'sideprj/window/realize',
		  },
          collapsed: true,
          items: [
            'sideprj/window/window_realize_f0_PlantModeling',
            'sideprj/window/window_realize_f0_VelMeasure',
            'sideprj/window/window_realize_f1_AutoManual',
            'sideprj/window/window_realize_f2_Profiling',
            'sideprj/window/window_realize_f3_FeedbackControl',
            'sideprj/window/window_realize_f4_Initialize',
            'sideprj/window/window_realize_f5_SoftStop',
            'sideprj/window/window_realize_f6_AntiPinch',
            'sideprj/window/window_realize_f7_KalmanFilter',
          ],
        },
        'sideprj/window/window_verify',
      ],
    },
    {
      type: 'category',
      label: '하이브리드 프로젝트',
	  link: {
        type: 'doc',
        id: 'sideprj/hybridprj',
      },
      collapsed: true,
      items: [
        'sideprj/hybridprj/esp32',
        'sideprj/hybridprj/linux',
      ],
    },
  ],
};
